  os: linux
  dist: focal
  group: edge
  language: generic
  sudo: required
  git:
    depth: 1
  addons:
    apt:
      update:
        - true
      packages:
        - aria2
        - zstd
        - xz-utils
services:
  - docker
before_install:
  - echo "${PASS}" | docker login -u "boedhack99" --password-stdin 2>/dev/null
  - docker pull ${DOCKER}
sudo: false
script:
  - bash build.sh
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d-%H%M')}
  - export RELEASE_NAME=mojito
  - git tag $TRAVIS_TAG
deploy:
    skip_cleanup: true
    provider: releases
    # The secret api_key will be loaded from the environment variables
    token: ${GTOKEN}
    file_glob: true
  file: /home/travis/rom/out/target/product/mojito/*.zip
    on:
      tags: false
      repo: boedhack/device_mojito
      branch: R
  branches:
    only:
      - R
    except:
      - /^(?i:untagged)-.*$/
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
